version: "3.7"

services:
  database:
    image: postgres
    container_name: database_pg
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    network_mode: host   
  api:
    build: .
    container_name: rentalx-api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on: 
      - database
    network_mode: host     
volumes:
  pgdata:
    driver: local