version: '3.7'

services:
  database:
    image: postgres
    container_name: database_pg
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/data/postgres
  api:
    build: .
    container_name: rentalx-api
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    depends_on:
      - database
volumes:
  pgdata:
    driver: local
