version: '3.7'

services:
  database:
    image: postgres
    container_name: database_pg
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  api:
    build: .
    container_name: rentalx-api
    volumes:
      - .:/usr/app
    depends_on:
      - database
    network_mode: host
volumes:
  pgdata:
    driver: local
